platform :ios, '8.0'
target "funpaw" do
pod "SDWebImage","~> 3.7.1"
pod "FMDB","~> 2.2"
pod 'MBProgressHUD', '~> 0.9'
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'AFNetworking', '~> 2.6.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'MOBFoundation'
pod 'MojoDatabase', '~> 1.4'
pod 'RMMapper', '~> 1.1.5'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'Masonry', '~> 0.6.0'
end
